[env]
live_config_reload = "true"
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
blur = false 
opacity = 0.93

[font]
size = 15
normal = { family = "Berkeley Mono NerdFont", style = "Regular" }
bold = { family = "Berkeley Mono NerdFont", style = "Bold" }
italic = { family = "Berkeley Mono NerdFont", style = "Italic" }
bold_italic = { family = "Berkeley Mono NerdFont", style = "Bold Italic" }
offset = { x = 0, y = 6 }

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#000000'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#000000'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 19
color = '#ff9e64'

[[colors.indexed_colors]]
index = 19
color = '#db4b4b'
